### ISSUE TITLE
Got Hopeful -- For a minute!

### ISSUE THREAD

**Issue by Blackhawke** [djlucas/LMSRoku#2]
Wow! I saw the name of the project "LMSRoku" and thought _perhaps_ someone was finally going to create a newer and better squeeze player for those of us who prefer the privacy of the Logitec Media Server system to the intrusive, and nosy PLEX option.

I hope you will at least consider doing so. "MainSqueeze" is the only app on Roku that supports LMS. It was abandoned five years ago, and the OS upgrade of last November broke it. 

Cheers!

**Comment by djlucas** [comment]
Sorry, just here for history. No changes. Closign.
